-- NyayaFlow AI — PostgreSQL schema (Postgres 14+).
--
-- The Node app uses SQLite by default (zero-setup).  To switch to Postgres:
--   1. docker compose up -d
--   2. export DATABASE_URL="postgres://nyaya:nyaya@localhost:5432/nyayaflow"
--   3. npm run db:migrate    # applies this file
--   4. npm run dev
--
-- The application code reads DATABASE_URL via lib/db.ts and selects the
-- matching driver.  The DDL below mirrors the SQLite schema 1:1.

CREATE TABLE IF NOT EXISTS judgments (
  id                  SERIAL PRIMARY KEY,
  file_name           TEXT NOT NULL,
  stored_path         TEXT,
  uploaded_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  status              TEXT NOT NULL DEFAULT 'Uploaded',
  page_count          INTEGER NOT NULL DEFAULT 0,
  is_scanned          INTEGER NOT NULL DEFAULT 0,
  source_text         TEXT,
  case_title          TEXT,
  case_number         TEXT,
  court_name          TEXT,
  order_date          TEXT,
  petitioners         TEXT,
  respondents         TEXT,
  urgency             TEXT,
  overall_confidence  REAL
);

CREATE TABLE IF NOT EXISTS extracted_fields (
  id                INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  judgment_id       INTEGER NOT NULL REFERENCES judgments(id) ON DELETE CASCADE,
  field_key         TEXT NOT NULL,
  ai_value          TEXT NOT NULL,
  current_value     TEXT NOT NULL,
  confidence        REAL NOT NULL,
  source_excerpt    TEXT NOT NULL,
  source_page       INTEGER NOT NULL,
  bbox              TEXT,
  status            TEXT NOT NULL DEFAULT 'Pending Review',
  reviewer_comment  TEXT,
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS action_items (
  id                    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  judgment_id           INTEGER NOT NULL REFERENCES judgments(id) ON DELETE CASCADE,
  title                 TEXT NOT NULL,
  ai_title              TEXT NOT NULL,
  action_type           TEXT NOT NULL,
  description           TEXT NOT NULL,
  ai_description        TEXT NOT NULL,
  department            TEXT NOT NULL,
  ai_department         TEXT NOT NULL,
  due_date              TEXT,
  ai_due_date           TEXT,
  needs_officer_review  INTEGER NOT NULL DEFAULT 0,
  source_excerpt        TEXT NOT NULL,
  source_page           INTEGER NOT NULL,
  bbox                  TEXT,
  confidence            REAL NOT NULL,
  urgency               TEXT NOT NULL DEFAULT 'Medium',
  status                TEXT NOT NULL DEFAULT 'Pending Review',
  reviewer_comment      TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  approved_by           TEXT,
  approved_at           TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS audit_log (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  judgment_id     INTEGER NOT NULL,
  entity_type     TEXT NOT NULL,
  entity_id       INTEGER NOT NULL,
  field_key       TEXT,
  ai_value        TEXT,
  previous_value  TEXT,
  new_value       TEXT,
  confidence      REAL,
  decision        TEXT NOT NULL,
  reviewer        TEXT NOT NULL,
  comment         TEXT,
  timestamp       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fields_judgment   ON extracted_fields(judgment_id);
CREATE INDEX IF NOT EXISTS idx_actions_judgment  ON action_items(judgment_id);
CREATE INDEX IF NOT EXISTS idx_actions_status    ON action_items(status);
CREATE INDEX IF NOT EXISTS idx_audit_judgment    ON audit_log(judgment_id);
